#!/bin/bash

sed '1,27d' |

sed '/<\/tr>/d' |

sed '731,747d' |

tr -d '[:blank:]' |

sed '/<tr>/d' |

sed '/<br>/d' |

sed 's/<[^>]*>//g' |

sed '/^$/d' |  

sed '1~2d' |

tr [:upper:] [:lower:] |

sed s/\`/\'/g |

sed "s/\,/\n/g" |

sed -r "/[^pk'mnwlhaeiou]+/d" |

sort -u
